
services:
  n8:
    image: n8nio/n8n
    container_name: n8
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - DB_POSTGRESDB_HOST=aws-0-us-east-2.pooler.supabase.com
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_TYPE=postgresdb

      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=50000
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - EXECUTIONS_TIMEOUT_MAX=7200
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http

      - WEBHOOK_URL=https://n8.9scloud.xyz
    volumes:
      - n_data:/home/node/.n8n

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - n8
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
volumes:
  n_data: