name: n8n

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  n8n:
    runs-on: ubuntu-latest

    env:  
      N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
      DB_POSTGRESDB_USER: ${{ secrets.DB_POSTGRESDB_USER }}
      DB_POSTGRESDB_PASSWORD: ${{ secrets.DB_POSTGRESDB_PASSWORD }}
      CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
      N8N_RUNNERS_AUTH_TOKEN: g86-io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Where
        run: curl https://ipinfo.io/json

      - name: Set up Docker Compose
        run: docker compose up

    


